// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artbuild.sql

package dbsqlc

import (
	"context"
	"strings"
)

const listArtBuildCandidates = `-- name: ListArtBuildCandidates :many
SELECT sc.image_url,
       CAST(GROUP_CONCAT(DISTINCT s.application) AS TEXT) AS applications,
       CAST(MIN(sc.component) AS TEXT) AS component,
       CAST(MIN(s.created_at) AS TEXT) AS first_seen,
       CAST(MAX(s.created_at) AS TEXT) AS last_seen
FROM snapshot_components sc
JOIN snapshots s ON s.id = sc.snapshot_id
LEFT JOIN art_builds a ON a.digest = substr(sc.image_url, instr(sc.image_url, '@') + 1)
WHERE instr(sc.image_url, '@sha256:') > 0
  AND (a.digest IS NULL OR (a.state = 'unresolved' AND a.checked_at < ?))
GROUP BY sc.image_url
ORDER BY last_seen DESC
LIMIT ?
`

type ListArtBuildCandidatesParams struct {
	CheckedAt string
	Limit     int64
}

type ListArtBuildCandidatesRow struct {
	ImageUrl     string
	Applications string
	Component    string
	FirstSeen    string
	LastSeen     string
}

// Stored component images with no ART record yet, or whose last miss is older
// than the retry cutoff, newest Snapshot first. first_seen bounds the build
// date: an image is built before any Snapshot holds it. applications lists every
// application holding the image, comma-separated.
func (q *Queries) ListArtBuildCandidates(ctx context.Context, arg ListArtBuildCandidatesParams) ([]ListArtBuildCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtBuildCandidates, arg.CheckedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtBuildCandidatesRow
	for rows.Next() {
		var i ListArtBuildCandidatesRow
		if err := rows.Scan(
			&i.ImageUrl,
			&i.Applications,
			&i.Component,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedArtBuilds = `-- name: ListResolvedArtBuilds :many
SELECT digest, state, nvr, record_id, upstream_repo, upstream_sha, checked_at
FROM art_builds
WHERE state = 'resolved' AND digest IN (/*SLICE:digests*/?)
`

func (q *Queries) ListResolvedArtBuilds(ctx context.Context, digests []string) ([]ArtBuild, error) {
	query := listResolvedArtBuilds
	var queryParams []interface{}
	if len(digests) > 0 {
		for _, v := range digests {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:digests*/?", strings.Repeat(",?", len(digests))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:digests*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtBuild
	for rows.Next() {
		var i ArtBuild
		if err := rows.Scan(
			&i.Digest,
			&i.State,
			&i.Nvr,
			&i.RecordID,
			&i.UpstreamRepo,
			&i.UpstreamSha,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtBuild = `-- name: UpsertArtBuild :exec
INSERT INTO art_builds (digest, state, nvr, record_id, upstream_repo, upstream_sha, checked_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(digest) DO UPDATE SET
    state = excluded.state,
    nvr = excluded.nvr,
    record_id = excluded.record_id,
    upstream_repo = excluded.upstream_repo,
    upstream_sha = excluded.upstream_sha,
    checked_at = excluded.checked_at
`

type UpsertArtBuildParams struct {
	Digest       string
	State        string
	Nvr          string
	RecordID     string
	UpstreamRepo string
	UpstreamSha  string
	CheckedAt    string
}

func (q *Queries) UpsertArtBuild(ctx context.Context, arg UpsertArtBuildParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtBuild,
		arg.Digest,
		arg.State,
		arg.Nvr,
		arg.RecordID,
		arg.UpstreamRepo,
		arg.UpstreamSha,
		arg.CheckedAt,
	)
	return err
}
