// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence.sql

package dbsqlc

import (
	"context"
)

const deleteScanEvidence = `-- name: DeleteScanEvidence :exec
DELETE FROM ticket_evidence WHERE snapshot_name = ? AND component = ? AND image_digest = ?
`

type DeleteScanEvidenceParams struct {
	SnapshotName string
	Component    string
	ImageDigest  string
}

func (q *Queries) DeleteScanEvidence(ctx context.Context, arg DeleteScanEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteScanEvidence, arg.SnapshotName, arg.Component, arg.ImageDigest)
	return err
}

const getCompleteScanByRange = `-- name: GetCompleteScanByRange :one
SELECT snapshot_name, component, image_digest, upstream_repo, base_sha, head_sha, state, reason, checked_at
FROM build_evidence_scans
WHERE upstream_repo = ? AND base_sha = ? AND head_sha = ? AND state = 'complete'
ORDER BY checked_at DESC
LIMIT 1
`

type GetCompleteScanByRangeParams struct {
	UpstreamRepo string
	BaseSha      string
	HeadSha      string
}

func (q *Queries) GetCompleteScanByRange(ctx context.Context, arg GetCompleteScanByRangeParams) (BuildEvidenceScan, error) {
	row := q.db.QueryRowContext(ctx, getCompleteScanByRange, arg.UpstreamRepo, arg.BaseSha, arg.HeadSha)
	var i BuildEvidenceScan
	err := row.Scan(
		&i.SnapshotName,
		&i.Component,
		&i.ImageDigest,
		&i.UpstreamRepo,
		&i.BaseSha,
		&i.HeadSha,
		&i.State,
		&i.Reason,
		&i.CheckedAt,
	)
	return i, err
}

const insertTicketEvidence = `-- name: InsertTicketEvidence :exec
INSERT INTO ticket_evidence (snapshot_name, component, image_digest, ticket_key, commit_sha, commit_url, pr_url, source, checked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTicketEvidenceParams struct {
	SnapshotName string
	Component    string
	ImageDigest  string
	TicketKey    string
	CommitSha    string
	CommitUrl    string
	PrUrl        string
	Source       string
	CheckedAt    string
}

func (q *Queries) InsertTicketEvidence(ctx context.Context, arg InsertTicketEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketEvidence,
		arg.SnapshotName,
		arg.Component,
		arg.ImageDigest,
		arg.TicketKey,
		arg.CommitSha,
		arg.CommitUrl,
		arg.PrUrl,
		arg.Source,
		arg.CheckedAt,
	)
	return err
}

const listEvidenceScans = `-- name: ListEvidenceScans :many
SELECT snapshot_name, component, image_digest, upstream_repo, base_sha, head_sha, state, reason, checked_at
FROM build_evidence_scans
WHERE snapshot_name = ?
ORDER BY component, image_digest
`

func (q *Queries) ListEvidenceScans(ctx context.Context, snapshotName string) ([]BuildEvidenceScan, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceScans, snapshotName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildEvidenceScan
	for rows.Next() {
		var i BuildEvidenceScan
		if err := rows.Scan(
			&i.SnapshotName,
			&i.Component,
			&i.ImageDigest,
			&i.UpstreamRepo,
			&i.BaseSha,
			&i.HeadSha,
			&i.State,
			&i.Reason,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotTicketEvidence = `-- name: ListSnapshotTicketEvidence :many
SELECT snapshot_name, component, image_digest, ticket_key, commit_sha, commit_url, pr_url, source, checked_at
FROM ticket_evidence
WHERE snapshot_name = ?
ORDER BY component, image_digest, ticket_key, commit_sha
`

func (q *Queries) ListSnapshotTicketEvidence(ctx context.Context, snapshotName string) ([]TicketEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotTicketEvidence, snapshotName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketEvidence
	for rows.Next() {
		var i TicketEvidence
		if err := rows.Scan(
			&i.SnapshotName,
			&i.Component,
			&i.ImageDigest,
			&i.TicketKey,
			&i.CommitSha,
			&i.CommitUrl,
			&i.PrUrl,
			&i.Source,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvidenceScan = `-- name: UpsertEvidenceScan :exec
INSERT INTO build_evidence_scans (snapshot_name, component, image_digest, upstream_repo, base_sha, head_sha, state, reason, checked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(snapshot_name, component, image_digest) DO UPDATE SET
    upstream_repo = excluded.upstream_repo,
    base_sha = excluded.base_sha,
    head_sha = excluded.head_sha,
    state = excluded.state,
    reason = excluded.reason,
    checked_at = excluded.checked_at
`

type UpsertEvidenceScanParams struct {
	SnapshotName string
	Component    string
	ImageDigest  string
	UpstreamRepo string
	BaseSha      string
	HeadSha      string
	State        string
	Reason       string
	CheckedAt    string
}

func (q *Queries) UpsertEvidenceScan(ctx context.Context, arg UpsertEvidenceScanParams) error {
	_, err := q.db.ExecContext(ctx, upsertEvidenceScan,
		arg.SnapshotName,
		arg.Component,
		arg.ImageDigest,
		arg.UpstreamRepo,
		arg.BaseSha,
		arg.HeadSha,
		arg.State,
		arg.Reason,
		arg.CheckedAt,
	)
	return err
}
