// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type Component struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   string
}

type JiraIssue struct {
	ID         int64
	Key        string
	Summary    string
	Status     string
	Priority   string
	Labels     string
	FixVersion string
	Assignee   string
	IssueType  string
	Resolution string
	Link       string
	QaContact  string
	UpdatedAt  string
}

type ReleaseVersion struct {
	ID                    int64
	Name                  string
	Description           string
	ReleaseDate           string
	Released              int64
	Archived              int64
	ReleaseTicketKey      string
	ReleaseTicketAssignee string
	S3Application         string
	DueDate               string
}

type Snapshot struct {
	ID          int64
	Application string
	Name        string
	CreatedAt   string
}

type SnapshotComponent struct {
	ID         int64
	SnapshotID int64
	Component  string
	GitSha     string
	ImageUrl   string
	GitUrl     string
}
