// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type ArtBuild struct {
	Digest       string
	State        string
	Nvr          string
	RecordID     string
	UpstreamRepo string
	UpstreamSha  string
	RebaseRepo   string
	RebaseSha    string
	PipelineUrl  string
	CheckedAt    string
}

type Component struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   string
}

type JiraIssue struct {
	ID         int64
	Key        string
	Summary    string
	Status     string
	Priority   string
	Labels     string
	FixVersion string
	Assignee   string
	IssueType  string
	Resolution string
	Link       string
	QaContact  string
	UpdatedAt  string
}

type KonfluxRelease struct {
	ID             int64
	Name           string
	Application    string
	Snapshot       string
	ReleasePlan    string
	Target         string
	ReleasedStatus string
	ReleasedReason string
	CreatedAt      string
	StartTime      string
	CompletionTime string
}

type ProwRun struct {
	JobName       string
	BuildID       string
	Kind          string
	Application   string
	State         string
	StartedAt     string
	CompletedAt   string
	ProwUrl       string
	ArtifactState string
	CatalogRef    string
	FetchedAt     string
}

type ProwRunImage struct {
	ID           int64
	JobName      string
	BuildID      string
	Role         string
	Source       string
	RequestedRef string
	Digest       string
	ImageID      string
}

type ProwSync struct {
	JobName            string
	Application        string
	IntervalSeconds    int64
	LastSuccessfulSync string
}

type ReleaseVersion struct {
	ID                    int64
	Name                  string
	Description           string
	ReleaseDate           string
	Released              int64
	Archived              int64
	ReleaseTicketKey      string
	ReleaseTicketAssignee string
	KonfluxApplication    string
	DueDate               string
}

type Snapshot struct {
	ID          int64
	Application string
	Name        string
	CreatedAt   string
}

type SnapshotComponent struct {
	ID         int64
	SnapshotID int64
	Component  string
	GitSha     string
	ImageUrl   string
	GitUrl     string
}
