// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scans.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const listImageScans = `-- name: ListImageScans :many
SELECT digest, state, pipeline_run, detail_url, counts_json, checked_at
FROM image_scans
WHERE digest IN (/*SLICE:digests*/?)
`

type ListImageScansRow struct {
	Digest      string
	State       string
	PipelineRun string
	DetailUrl   string
	CountsJson  sql.NullString
	CheckedAt   string
}

func (q *Queries) ListImageScans(ctx context.Context, digests []string) ([]ListImageScansRow, error) {
	query := listImageScans
	var queryParams []interface{}
	if len(digests) > 0 {
		for _, v := range digests {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:digests*/?", strings.Repeat(",?", len(digests))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:digests*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImageScansRow
	for rows.Next() {
		var i ListImageScansRow
		if err := rows.Scan(
			&i.Digest,
			&i.State,
			&i.PipelineRun,
			&i.DetailUrl,
			&i.CountsJson,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImageScan = `-- name: UpsertImageScan :exec
INSERT INTO image_scans (digest, state, pipeline_run, detail_url, counts_json, reports_json, checked_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(digest) DO UPDATE SET
    state = excluded.state,
    pipeline_run = excluded.pipeline_run,
    detail_url = excluded.detail_url,
    counts_json = excluded.counts_json,
    reports_json = excluded.reports_json,
    checked_at = excluded.checked_at
`

type UpsertImageScanParams struct {
	Digest      string
	State       string
	PipelineRun string
	DetailUrl   string
	CountsJson  sql.NullString
	ReportsJson sql.NullString
	CheckedAt   string
}

func (q *Queries) UpsertImageScan(ctx context.Context, arg UpsertImageScanParams) error {
	_, err := q.db.ExecContext(ctx, upsertImageScan,
		arg.Digest,
		arg.State,
		arg.PipelineRun,
		arg.DetailUrl,
		arg.CountsJson,
		arg.ReportsJson,
		arg.CheckedAt,
	)
	return err
}
