// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package dbsqlc

import (
	"context"
	"strings"
)

const createSnapshot = `-- name: CreateSnapshot :execlastid
INSERT INTO snapshots (application, name, created_at)
VALUES (?, ?, ?)
`

type CreateSnapshotParams struct {
	Application string
	Name        string
	CreatedAt   string
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSnapshot, arg.Application, arg.Name, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createSnapshotComponent = `-- name: CreateSnapshotComponent :exec
INSERT INTO snapshot_components (snapshot_id, component, image_url)
VALUES (?, ?, ?)
`

type CreateSnapshotComponentParams struct {
	SnapshotID int64
	Component  string
	ImageUrl   string
}

func (q *Queries) CreateSnapshotComponent(ctx context.Context, arg CreateSnapshotComponentParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshotComponent, arg.SnapshotID, arg.Component, arg.ImageUrl)
	return err
}

const getSnapshotRow = `-- name: GetSnapshotRow :one
SELECT id, application, name, created_at
FROM snapshots WHERE name = ?
`

func (q *Queries) GetSnapshotRow(ctx context.Context, name string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotRow, name)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listComponentCandidates = `-- name: ListComponentCandidates :many
SELECT sc.id, sc.component, sc.image_url,
       s.id AS snapshot_id, s.application, s.created_at
FROM snapshot_components sc
JOIN snapshots s ON s.id = sc.snapshot_id
WHERE s.application IN (/*SLICE:applications*/?)
`

type ListComponentCandidatesRow struct {
	ID          int64
	Component   string
	ImageUrl    string
	SnapshotID  int64
	Application string
	CreatedAt   string
}

func (q *Queries) ListComponentCandidates(ctx context.Context, applications []string) ([]ListComponentCandidatesRow, error) {
	query := listComponentCandidates
	var queryParams []interface{}
	if len(applications) > 0 {
		for _, v := range applications {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:applications*/?", strings.Repeat(",?", len(applications))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:applications*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentCandidatesRow
	for rows.Next() {
		var i ListComponentCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Component,
			&i.ImageUrl,
			&i.SnapshotID,
			&i.Application,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotComponents = `-- name: ListSnapshotComponents :many
SELECT id, snapshot_id, component, image_url
FROM snapshot_components
WHERE snapshot_id = ?
ORDER BY component
`

func (q *Queries) ListSnapshotComponents(ctx context.Context, snapshotID int64) ([]SnapshotComponent, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotComponents, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotComponent
	for rows.Next() {
		var i SnapshotComponent
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Component,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamSnapshotsWithDigest = `-- name: ListStreamSnapshotsWithDigest :many
SELECT name
FROM snapshots s
WHERE application = ?1 AND name NOT LIKE 'fbc-ri-%'
  AND NOT EXISTS (SELECT 1 FROM staged_snapshots ss WHERE ss.name = s.name)
  AND EXISTS (SELECT 1 FROM snapshot_components sc
              WHERE sc.snapshot_id = s.id
                AND substr(sc.image_url, instr(sc.image_url, '@') + 1) = CAST(?2 AS TEXT))
ORDER BY created_at DESC, name DESC
`

type ListStreamSnapshotsWithDigestParams struct {
	Application string
	Digest      string
}

// The stream builds, as NewestStreamSnapshot filters them, holding an image
// of the digest, newest first.
func (q *Queries) ListStreamSnapshotsWithDigest(ctx context.Context, arg ListStreamSnapshotsWithDigestParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStreamSnapshotsWithDigest, arg.Application, arg.Digest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newestStreamSnapshot = `-- name: NewestStreamSnapshot :one
SELECT name
FROM snapshots s
WHERE application = ? AND name NOT LIKE 'fbc-ri-%'
  AND NOT EXISTS (SELECT 1 FROM staged_snapshots ss WHERE ss.name = s.name)
ORDER BY created_at DESC, name DESC
LIMIT 1
`

// ART's assembly Snapshots (staged_snapshots) and its fbc-ri-* re-releases of
// a bundle's related images are not stream builds.
func (q *Queries) NewestStreamSnapshot(ctx context.Context, application string) (string, error) {
	row := q.db.QueryRowContext(ctx, newestStreamSnapshot, application)
	var name string
	err := row.Scan(&name)
	return name, err
}

const snapshotExistsByName = `-- name: SnapshotExistsByName :one
SELECT COUNT(*) FROM snapshots WHERE name = ?
`

func (q *Queries) SnapshotExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, snapshotExistsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
