// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package dbsqlc

import (
	"context"
	"strings"
)

const createSnapshot = `-- name: CreateSnapshot :execlastid
INSERT INTO snapshots (application, name, created_at)
VALUES (?, ?, ?)
`

type CreateSnapshotParams struct {
	Application string
	Name        string
	CreatedAt   string
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSnapshot, arg.Application, arg.Name, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createSnapshotComponent = `-- name: CreateSnapshotComponent :exec
INSERT INTO snapshot_components (snapshot_id, component, git_sha, image_url, git_url)
VALUES (?, ?, ?, ?, ?)
`

type CreateSnapshotComponentParams struct {
	SnapshotID int64
	Component  string
	GitSha     string
	ImageUrl   string
	GitUrl     string
}

func (q *Queries) CreateSnapshotComponent(ctx context.Context, arg CreateSnapshotComponentParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshotComponent,
		arg.SnapshotID,
		arg.Component,
		arg.GitSha,
		arg.ImageUrl,
		arg.GitUrl,
	)
	return err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, application, name, created_at
FROM snapshots WHERE id = ?
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByID, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotRow = `-- name: GetSnapshotRow :one
SELECT id, application, name, created_at
FROM snapshots WHERE name = ?
`

func (q *Queries) GetSnapshotRow(ctx context.Context, name string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotRow, name)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAllSnapshots = `-- name: ListAllSnapshots :many
SELECT id, application, name, created_at
FROM snapshots
ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListAllSnapshotsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllSnapshots(ctx context.Context, arg ListAllSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllSnapshots, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Application,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentCandidates = `-- name: ListComponentCandidates :many
SELECT sc.id, sc.component, sc.git_sha, sc.image_url, sc.git_url,
       s.id AS snapshot_id, s.application, s.name AS snapshot, s.created_at
FROM snapshot_components sc
JOIN snapshots s ON s.id = sc.snapshot_id
WHERE s.application IN (/*SLICE:applications*/?)
`

type ListComponentCandidatesRow struct {
	ID          int64
	Component   string
	GitSha      string
	ImageUrl    string
	GitUrl      string
	SnapshotID  int64
	Application string
	Snapshot    string
	CreatedAt   string
}

func (q *Queries) ListComponentCandidates(ctx context.Context, applications []string) ([]ListComponentCandidatesRow, error) {
	query := listComponentCandidates
	var queryParams []interface{}
	if len(applications) > 0 {
		for _, v := range applications {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:applications*/?", strings.Repeat(",?", len(applications))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:applications*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentCandidatesRow
	for rows.Next() {
		var i ListComponentCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Component,
			&i.GitSha,
			&i.ImageUrl,
			&i.GitUrl,
			&i.SnapshotID,
			&i.Application,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseSnapshots = `-- name: ListReleaseSnapshots :many
SELECT id, application, name, created_at
FROM snapshots s
WHERE s.application IN (/*SLICE:applications*/?)
  AND (s.application != ?
       OR EXISTS (SELECT 1 FROM snapshot_components sc
                  WHERE sc.snapshot_id = s.id AND sc.component LIKE ?))
ORDER BY s.created_at DESC, s.id DESC
LIMIT ? OFFSET ?
`

type ListReleaseSnapshotsParams struct {
	Applications []string
	Application  string
	Component    string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListReleaseSnapshots(ctx context.Context, arg ListReleaseSnapshotsParams) ([]Snapshot, error) {
	query := listReleaseSnapshots
	var queryParams []interface{}
	if len(arg.Applications) > 0 {
		for _, v := range arg.Applications {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:applications*/?", strings.Repeat(",?", len(arg.Applications))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:applications*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Application)
	queryParams = append(queryParams, arg.Component)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Application,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotComponents = `-- name: ListSnapshotComponents :many
SELECT id, snapshot_id, component, git_sha, image_url, git_url
FROM snapshot_components
WHERE snapshot_id = ?
ORDER BY component
`

func (q *Queries) ListSnapshotComponents(ctx context.Context, snapshotID int64) ([]SnapshotComponent, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotComponents, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotComponent
	for rows.Next() {
		var i SnapshotComponent
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Component,
			&i.GitSha,
			&i.ImageUrl,
			&i.GitUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByApplication = `-- name: ListSnapshotsByApplication :many
SELECT id, application, name, created_at
FROM snapshots
WHERE application = ?
ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListSnapshotsByApplicationParams struct {
	Application string
	Limit       int64
	Offset      int64
}

func (q *Queries) ListSnapshotsByApplication(ctx context.Context, arg ListSnapshotsByApplicationParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByApplication, arg.Application, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Application,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotExistsByName = `-- name: SnapshotExistsByName :one
SELECT COUNT(*) FROM snapshots WHERE name = ?
`

func (q *Queries) SnapshotExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, snapshotExistsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
