// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staged.sql

package dbsqlc

import (
	"context"
)

const latestStagedSnapshot = `-- name: LatestStagedSnapshot :one
SELECT name, assembly, kind, env, created_at
FROM staged_snapshots
WHERE assembly = ? AND kind = ? AND env = 'stage'
ORDER BY created_at DESC, name DESC
LIMIT 1
`

type LatestStagedSnapshotParams struct {
	Assembly string
	Kind     string
}

func (q *Queries) LatestStagedSnapshot(ctx context.Context, arg LatestStagedSnapshotParams) (StagedSnapshot, error) {
	row := q.db.QueryRowContext(ctx, latestStagedSnapshot, arg.Assembly, arg.Kind)
	var i StagedSnapshot
	err := row.Scan(
		&i.Name,
		&i.Assembly,
		&i.Kind,
		&i.Env,
		&i.CreatedAt,
	)
	return i, err
}

const upsertStagedSnapshot = `-- name: UpsertStagedSnapshot :exec
INSERT INTO staged_snapshots (name, assembly, kind, env, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    assembly=excluded.assembly,
    kind=excluded.kind,
    env=excluded.env,
    created_at=excluded.created_at
`

type UpsertStagedSnapshotParams struct {
	Name      string
	Assembly  string
	Kind      string
	Env       string
	CreatedAt string
}

func (q *Queries) UpsertStagedSnapshot(ctx context.Context, arg UpsertStagedSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertStagedSnapshot,
		arg.Name,
		arg.Assembly,
		arg.Kind,
		arg.Env,
		arg.CreatedAt,
	)
	return err
}
