// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staged.sql

package dbsqlc

import (
	"context"
)

const latestStagedSnapshot = `-- name: LatestStagedSnapshot :one
SELECT name, assembly, kind, env, created_at
FROM staged_snapshots
WHERE assembly = ? AND kind = ? AND env = 'stage'
ORDER BY created_at DESC, name DESC
LIMIT 1
`

type LatestStagedSnapshotParams struct {
	Assembly string
	Kind     string
}

func (q *Queries) LatestStagedSnapshot(ctx context.Context, arg LatestStagedSnapshotParams) (StagedSnapshot, error) {
	row := q.db.QueryRowContext(ctx, latestStagedSnapshot, arg.Assembly, arg.Kind)
	var i StagedSnapshot
	err := row.Scan(
		&i.Name,
		&i.Assembly,
		&i.Kind,
		&i.Env,
		&i.CreatedAt,
	)
	return i, err
}

const listSuccessfulStageReleases = `-- name: ListSuccessfulStageReleases :many
SELECT kr.name AS release_name, kr.release_plan, kr.completion_time,
       s.id AS snapshot_id, s.name AS snapshot_name, s.created_at AS snapshot_created_at
FROM staged_snapshots ss
JOIN snapshots s ON s.name = ss.name
JOIN konflux_releases kr ON kr.snapshot = s.name AND kr.application = s.application
WHERE ss.assembly = ?1 AND ss.kind = 'image' AND ss.env = 'stage'
  AND s.application = ?2
  AND kr.released_status = 'True' AND kr.released_reason = 'Succeeded' AND kr.completion_time != ''
ORDER BY kr.completion_time DESC, kr.created_at DESC, kr.name DESC
`

type ListSuccessfulStageReleasesParams struct {
	Assembly    string
	Application string
}

type ListSuccessfulStageReleasesRow struct {
	ReleaseName       string
	ReleasePlan       string
	CompletionTime    string
	SnapshotID        int64
	SnapshotName      string
	SnapshotCreatedAt string
}

func (q *Queries) ListSuccessfulStageReleases(ctx context.Context, arg ListSuccessfulStageReleasesParams) ([]ListSuccessfulStageReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuccessfulStageReleases, arg.Assembly, arg.Application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuccessfulStageReleasesRow
	for rows.Next() {
		var i ListSuccessfulStageReleasesRow
		if err := rows.Scan(
			&i.ReleaseName,
			&i.ReleasePlan,
			&i.CompletionTime,
			&i.SnapshotID,
			&i.SnapshotName,
			&i.SnapshotCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStagedSnapshot = `-- name: UpsertStagedSnapshot :exec
INSERT INTO staged_snapshots (name, assembly, kind, env, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    assembly=excluded.assembly,
    kind=excluded.kind,
    env=excluded.env,
    created_at=excluded.created_at
`

type UpsertStagedSnapshotParams struct {
	Name      string
	Assembly  string
	Kind      string
	Env       string
	CreatedAt string
}

func (q *Queries) UpsertStagedSnapshot(ctx context.Context, arg UpsertStagedSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertStagedSnapshot,
		arg.Name,
		arg.Assembly,
		arg.Kind,
		arg.Env,
		arg.CreatedAt,
	)
	return err
}
